version: "3.7"

services:
  versetime-api:
    container_name: versetime-api
    image: node:20-alpine
    ports:
      - "5001:5001"
    working_dir: /app
    volumes:
      - .:/app:cached
    command: sh -c "npm install; npm run start"
    environment:
      - NODE_ENV=development

  versetime-caddy:
    container_name: versetime-caddy
    image: caddy/caddy:2.2.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - $PWD/Caddyfile:/etc/caddy/Caddyfile
     - $PWD/ca-certificates:/data/caddy/pki/authorities/local
     - caddy_data:/data
     - caddy_config:/config

  versetime-db:
    container_name: versetime-db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bible
    ports:
      - "5432:5432"
    volumes:
      - $PWD/bootstrap.sql:/docker-entrypoint-initdb.d/dump.sql
      - pg_data:/var/lib/postgresql/data/

volumes:
  caddy_data:
  caddy_config:
  pg_data:
