services:
  versetime-db:
    container_name: versetime-db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bible
    ports:
      - "5432:5432"
    volumes:
      - $PWD/bootstrap.sql:/docker-entrypoint-initdb.d/dump.sql
      # - pg_data:/var/lib/postgresql/data/
      - $PWD/bsb-insert.sql:/bible-data/bsb-insert.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d bible"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
